services:
  weaviate:
    image: semitechnologies/weaviate:latest
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      - QUERY_DEFAULTS_LIMIT=25
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - ENABLE_GRPC=true
    
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - WEAVIATE_URL=http://weaviate:8080
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    depends_on:
      - weaviate

  viz:
    build: 
      context: .
      dockerfile: src/logger/viz/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./logs:/app/logs
    depends_on:
      - api

volumes:
  weaviate_data: 